import type {Metadata} from "next";
import "./globals.css";
import React from "react";

import AdSense from "@/components/AdSense";
import Wordmark from "@/app/Wordmark";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <AdSense pId={"1921734779513180"}/>
            <title>SummaryLib</title>
        </head>
        <body

        >
        <div className={`h-screen flex flex-col `}>
            <div className={"flex flex-row justify-between"}>
                <Wordmark/>
            </div>
            <div className="grow flex ">{children}</div>
        </div>

        </body>
        </html>
    );
}
