import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import React from "react";
import Image from "next/image";
import AdSense from "@/components/AdSense";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head><AdSense pId={"1921734779513180"}/></head>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-screen`}
        >
        <div className={"flex flex-row justify-between"}>
            <p className="font-serif">SummaryLib</p>
            <div><p>Search</p></div>
            <div><Image src="/vercel.svg" alt="Dummy img" width={50} height={50}/></div>
        </div>
        <div className="flex">{children}</div>
        </body>
        </html>
    );
}
